# -*- coding: utf-8 -*-
"""latihanML1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nWtpoC4DGFk08Xj-zMvi_r-HW48pJdsK
"""

import os
os.listdir('sample_data')

import pandas as pd

df = pd.read_csv('sample_data/california_housing_train.csv')
df.head()

from sklearn.preprocessing import MinMaxScaler
data = [[12000000, 33], [35000000, 45], [4000000, 23], [6500000, 26], [9000000, 29]]
scaler = MinMaxScaler()
scaler.fit(data)
print(scaler.transform(data))

"""print(scaler.fit(data))"""

from sklearn.model_selection import train_test_split

X_data = range(10)
y_data = range(10)

 #kita membagi array X dan y ke dalam 20% data testing (test_size=0.2 ).
print("random_state ditentukan")
for i in range(3):
    X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size = 0.3, random_state = 42)
    print(y_test)

 #Proses shuffling menjaga rasio informasi pada data training dan testing tetap berimbang.
print("random_state tidak ditentukan")
for i in range(3):
    X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size = 0.3, random_state = None)
    print(y_test)

