# -*- coding: utf-8 -*-
"""Latihan2_Sklearn_Train_Test_Split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WLORwkaqSXBU-XlpxQZpe-wocSXWYCSI
"""

import sklearn
from sklearn import datasets

# load iris dataset
iris = datasets.load_iris()

# pisahkan atribut dan label pada iris dataset
x=iris.data
y=iris.target

from sklearn.model_selection import train_test_split

# membagi dataset menjadi training dan testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# menghitung panjang/jumlah data pada masing-masing direktori split
print(len(x))
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

###---------------------------------------------------CROSS VALIDASI---------------------------------------------------###
from sklearn import tree

# membuat model dengan decision tree classifier
clf = tree.DecisionTreeClassifier()

from sklearn.model_selection import cross_val_score

# mengevaluasi performa model dengan cross_val_score
scores = cross_val_score(clf, x, y, cv=5)

'''Elemen pertama dari larik menunjukkan nilai 0.96666 yang berarti
ketika fold pertama dijadikan validation set dan fold lainnya dijadikan
train set, hasil dari pengujian tersebut adalah akurasi sebesar 0.96666. '''

