# -*- coding: utf-8 -*-
"""latihan9-10-SVC-dan-SVR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3OP-7COboTfgSrPs5SOw6zVM4L_NIw-
"""

'''
Tahapan latihan kali ini adalah:

Ubah data ke dalam Dataframe.
Bagi dataset.
Lakukan standarisasi.
Buat dan latih model.
Evaluasi model
.'''

import pandas as pd

df = pd.read_csv('diabetes.csv')

df.head()

#dataframe
df.info()

# memisahkan atribut pada dataset dan menyimpannya pada sebuah variabel X
X = df[df.columns[:8]]

# memisahkan label pada dataset dan menyimpannya pada sebuah variabel Y
y = df['Outcome']

from sklearn.preprocessing import StandardScaler

# standarisasi nilai-nilai dari dataset
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

from sklearn.model_selection import train_test_split

# memisahkan data untuk training dan testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

# ----------------------------------------SUPPORT VECTOR-------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------
from sklearn.svm import SVC

# membuat objek SVC dan memanggil fungsi fit untuk melatih model
clf = SVC()
clf.fit(X_train, y_train)

# Menampilkan skor akurasi prediksi
clf.score(X_test, y_test)
#model Support Vector Classifier untuk mendeteksi diabetes.

# ---------------------------------------------SVR-------------------------------------------------------
# ---------------------------------------------SVR-------------------------------------------------------
# ---------------------------------------------SVR-------------------------------------------------------
# ---------------------------------------------SVR-------------------------------------------------------
# ---------------------------------------------SVR-------------------------------------------------------
# ---------------------------------------------SVR-------------------------------------------------------
# ---------------------------------------------SVR-------------------------------------------------------
# ---------------------------------------------SVR-------------------------------------------------------
# ---------------------------------------------SVR-------------------------------------------------------
# ---------------------------------------------SVR-------------------------------------------------------

'''
Tahapan pada latihan kali ini adalah sebagai berikut:

Ubah data menjadi Dataframe.
Pisahkan atribut dan label.
Latih model SVR.
Buat plot dari model.
'''

import pandas as pd
# membaca dataset dan mengubahnya menjadi dataframe
data = pd.read_csv('Salary_Data.csv')
data.info()

data.head()

# Kemudian kita pisahkan antara atribut dan label yang ingin diprediksi.
import numpy as np

# memisahkan atribut dan label
X = data['YearsExperience']
y = data['Salary']

# mengubah bentuk atribut
X = np.array(X)
X = X[:,np.newaxis]

# Berikutnya kita buat objek support vector regression dan di sini kita
# akan mencoba menggunakan parameter C = 1000, gamma = 0.05, dan kernel ‘rbf’.
from sklearn.svm import SVR

# membangun model dengan parameter C, gamma, dan kernel
model  = SVR(C=1000, gamma=0.05, kernel='rbf')

# Setelah model dibuat kita akan melatih model dengan fungsi fit pada data.
# melatih model dengan fungsi fit
model.fit(X,y)

import matplotlib.pyplot as plt

# memvisualisasikan model
plt.scatter(X, y)
plt.plot(X, model.predict(X))
# Hasil visualisasi menunjukkan bahwa model yang kita kembangkan,
# belum mampu menyesuaikan terhadap pola pada data dengan baik