# -*- coding: utf-8 -*-
"""LatihanML 3-4 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irS3TduI42dj7LFzUczvCeS-76RR8Vab
"""

import pandas as pd
from sklearn.datasets import load_iris

# membaca file iris.csv
iris = pd.read_csv('Iris.csv')

# melihat informasi dataset pada 5 baris pertama
iris.head()

# menghilangkan kolom yang tidak penting
iris.drop('Id',axis=1,inplace=True)

# memisahkan atribut dan label
X = iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm' ]]
y = iris['Species']

# Membagi dataset menjadi data latih & data uji
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=123)


# X_train , y_train adalah subset dari atribut yang digunakan untuk melatih model
# X_test adalah subset dari atribut yang digunakan untuk menguji model.

# x_test adalah subset dari target yang sesuai dengan X_test
# y_test adalah subset dari target yang sesuai dengan y_test

# test_size=0.1 berarti 10% dari data akan digunakan sebagai data uji,
# sementara 90% akan digunakan sebagai data latih.

# random_state adalah nilai yang digunakan untuk menghasilkan
# pembagian data yang konsisten setiap kali kode dijalankan

from sklearn.tree import DecisionTreeClassifier

# membuat model Decision Tree
tree_model = DecisionTreeClassifier()

# melakukan pelatihan model terhadap data
tree_model = tree_model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = tree_model.predict(X_test)

acc_secore = round(accuracy_score(y_pred, y_test), 3)

print('Accuracy: ', acc_secore)

# prediksi model dengan tree_model.predict([[SepalLength, SepalWidth, PetalLength, PetalWidth]])
print(tree_model.predict([[6.2, 3.4, 5.4, 2.3]])[0])

from sklearn.tree import export_graphviz
export_graphviz(
    tree_model,
    out_file = "iris_tree.dot",
    feature_names = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'],
    class_names = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica' ],
    rounded= True,
    filled =True
)

